services:
  backend-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${BK_POSTGRES_DB}
      POSTGRES_USER: ${BK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BK_POSTGRES_PASSWORD}
    ports:
        - "5432:5432"
    volumes:
        - backend_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:26.3
    command: start-dev
    environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
        KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
        KC_HTTP_ENABLED: true
        KC_HOSTNAME_STRICT: false
        KC_HOSTNAME_STRICT_HTTPS: false
    ports:
        - "8282:8080"
    restart: always

volumes:
  backend_data:
    driver: local